//
//  File.swift
//  
//
//  Created by Michael Geurtjens on 23/5/2023.
//

import Foundation
/// collection of words in the crozzle game and used for testing of the structures in this package
public struct WordData {
    
    public static func words_8612() -> [String] {
        return [
            "ZION","AZURE","TOYS","JOY","HAZELNUT","NUTS","NAZARETH","HYMN","TURKEY","SNOW",
            "MERRY","TOAST","STAR","HOLLY","JELLY","FAMILY","WHITE","SING","SAUCE","PORK",
            "TREE","EVE","INN","BELLS","CAKE","GLAZE","PARTYHATS","TWENTYFIFTH","WALNUT","PEANUTS",
            "PRESENTS","FRUIT","NUTMEG","CUSTARD","CHRISTMAS","MISTLETOE","GIFTS","SANTACLAUS","FESTIVE","RAISINS",
            "LIGHTS","WREATH","HOLIDAY","WISEMEN","CRANBERRY","OPENHOUSE","SILENTNIGHT","STOCKING","PUNCH","WINE",
            "SHOPPING","PLUMPUDDING","WRAPPING","NEIGHBOURS","GREETINGS","DECORATIONS","ALMONDS","LANTERN","KRISSKRINGLE","SPICE",
            "GOODWILL","BONBON","CHURCH","FRIENDS","PARCELS","CINNAMON","NICHOLAS","MINCEPIES","CHERRIES","SLEIGH",
            "ALMOND","MANGER","RIBBON","CHOCOLATE","MIXEDPEEL","DRINK","CANDLES","FOOD","GINGER","BETHLEHEM",
            "CAROL","REINDEER","GOODCHEER","CREAM","CORDIAL","CHILDREN","ICECREAM","CHICKEN","CARD","DECEMBER",
            "PEACE"]
    }
    
    public static func words_8804() -> [String] {
        return [ "MEZZO","MAZURKA","HYMN","STRUM","KEY","STOP","SLOW","SLUR","MUTE","REST",
                 "TUNE","HUM","LOW","SONG","TRIO","BASSO","DUO","NOTE","TONE","TEMPO",
                 "HIT","SIGN","TIME","TIE","FORTE","SCORE","FRET","VIOLA","MOOD","HARP",
                 "MARCH","HOLD","ARIA","ECHO","JAZZ","WALTZ","PIZZICATO","SYMPHONY","OPUS","RHYTHM",
                 "TRUMPET","SYNCOPATE","HARMONY","RHAPSODY","XYLOPHONE","LUTE","OVERTURE","MELODY","STRING","GAMUT",
                 "LULLABY","BASS","DUET","SOLO","CHORUS","MINUET","VOLUME","PAUSE","QUAVER","SONATA",
                 "DRUM","MOVEMENT","NOCTURNE","TENOR","CYMBAL","GUITAR","SOPRANO","FLUTE","FUGUE","NATURAL",
                 "SAXOPHONE","CONDUCTOR","TREMOLO","OCTAVE","ETUDE","SHARP","STAFF","TACET","ALTO","INTERVAL",
                 "KEYBOARD","TROMBONE","CORNET","VIOLIN","ORCHESTRA","CANTO","MINOR","HORN","LILT","DULCET",
                 "CANTATA","PITCH","QUICK","CONCERTO","POLONAISE","MINIM","THEME","BARITONE","FLAT","BREVE",
                 "MAJOR","ORGAN","PIANO","BUNGLE","LEGATO","PRELUDE","OBLIGATO","CLARINET","ANDANTE","TREBLE",
                 "OPERA","CRESCENDO","BEAT","PIPE","SERENADE","LARGO","POLKA","SCALE","PICCOLO","OBOE",
                 "ENCORE","ARPEGGIO","BANJO","CAROL","CHORD","ALLEGRO","BAR","JIG","HIGH","REEL",
                 "CHIME","FANFARE","ADAGIO","PEDAL","BAND","CODA","REED","BALLAD","CLEF","FIFE"]
    }
    
    public static func words_8802() -> [String] {
        return [ "PRIZE","STUDY","GYM","BOYS","SUMS","SWOT","BLAZER","COPY","PHYSICS","PLAY",
                 "SPORT","CRAYON","MATHS","QUIET","TENNIS","MATES","ART","TERM","CLASS","TABLES",
                 "LINES","CAPTAIN","PEN","ROLL","INK","CANE","HISTORY","STUDENT","SONGS","CHEMISTRY",
                 "PRIMARY","GEOMETRY","ROSTER","SETSQUARE","TUCKSHOP","MUSIC","PLAYGROUND","SEAT","HOLIDAYS","TEXTBOOK",
                 "LABORATORY","SECONDARY","BIOLOGY","WOODWORK","BURSAR","MASTER","COMPASS","LIBRARY","MONITOR","WRITING",
                 "POEMS","PROTRACTOR","SPANISH","PUPIL","JUNIOR","PROJECTS","GEOGRAPHY","UNIFORM","RECESS","SENIOR",
                 "BOOKS","RULER","OVAL","HSC","FRACTIONS","HOMEWORK","VACATION","GIRLS","LECTURE","PARSING",
                 "EXAM","SCHOOL","LUNCH","EDUCATION","FORM","LANGUAGES","CALCULATOR","ERASER","RUBBER","DRAWING",
                 "SPELLING","TIMETABLE","HEADMASTER","INDONESIAN","DESK","ENGLISH","FRIENDS","SHAKESPEARE","FOOTBALL","GRAMMAR",
                 "ITALIAN","PREFECT","SPEECH","PAPER","COOKING","CRICKET","GERMAN","PRINCIPAL","SCIENCE","TEACHER",
                 "CRAM","FOOD","DECIMALS","LOCKER","PENCIL","FRENCH","READING","CHAIR","REFERENCE","COLLEGE",
                 "BLACKBOARD","ALGEBRA","CHALK","BELL","FLAG"]
    }
    
    public static func words_8711() -> [String] {
        return [ "AZURE","ZOFFANY","SOOTY","RUBY","BAY","RUDDY","SANDY","GOYA","GREY","EBONY","DYCK","BRUSH","TUBE","ART","DUN","RUBENS","TAN","TONE","COROT","COLOUR","PAINT","ROUGE","HUE","JET","UMBER","SEPIA","BLUE","AMBER","RED","LAKE","LAC","JADE","TAWNY","CEZANNE","RUSSET","SCOTT","ROMNEY","YELLOW","TEXTURE","ROSSETTI","LELY","TINTORETTO","REYNOLDS","TURNER","MIX","STAIN","MATISSE","MAUVE","WHISTLER","AUBURN","UTRILLO","BROWN","MONET","WHITE","SILVER","TITIAN","VIOLET","PICASSO","SARGENT","BEARDSLEY","CRIMSON","GAUGUIN","CANVAS","PURPLE","MURILLO","SICKERT","OPAQUE","MANET","PALETTE","PIGMENT","SCARLET","FAWN","GILT","PUCE","MAROON","GAINSBOROUGH","VERMILION","OLIVE","ORPEN","CANALETTO","CONSTABLE","HOGARTH","RAEBURN","SAFFRON","VERMEER","HALS","SAPPHIRE","MILLET","RENOIR","REMBRANDT","BOTTICELLI","JOHN","PINK","NOLAN","LACQUER","MAGENTA","MILLAIS","CERISE","CLARET","COBALT","BUFF","OPIE","LANDSEER","LAVENDER","LAWRENCE","CHROME","ORANGE","CHOCOLATE","DEGAS","EASEL","INDIGO","FRAGONARD","CORAL","GREEN","HENNA","MODEL","OCHRE","GOLDEN","HOLBEIN","ANIL","CREAM","ENAMEL","MICHELANGELO","RAPHAEL","DRAB","BEIGE","BLACK","BICE"]
    }
    
    public static func words_8803() -> [String] {
        return [ "SUEZ","ZURICH","SYDNEY","AYR","TOKYO","YORK","QUITO","TORONTO","BOMBAY","OMSK","OSLO","LAGOS","BOGOTA","HOBART","TOLEDO","BONN","RENO","ROME","OSAKA","CORK","CAIRO","OMAHA","LIMA","DELHI","TUCSON","HOUSTON","TULSA","BUTTE","TURIN","OTTAWA","WARSAW","BRUSSELS","BOSTON","MOSCOW","PITTSBURGH","SEOUL","VANCOUVER","HONOLULU","ISTANBUL","TASHKENT","YOKOHAMA","SEATTLE","ATHENS","JUNEAU","DETROIT","STOCKHOLM","CALGARY","GLASGOW","PARIS","PERTH","BUCHAREST","CALCUTTA","EDMONTON","SANTIAGO","OXFORD","ATLANTA","MEMPHIS","PHOENIX","AMSTERDAM","LISBON","MUNICH","MONTREAL","JERUSALEM","LIVERPOOL","HAMILTON","WINNIPEG","DARWIN","NAPLES","PRAGUE","VIENNA","SINGAPORE","RANGOON","NOME","MELBOURNE","BOISE","DENVER","LONDON","MADRAS","BELFAST","BATH","DUBLIN","GDANSK","TEHERAN","HAVANA","BRISBANE","SHANGHAI","JAKARTA","QUEBEC","NAGASAKI","HANOI","MIAMI","BUFFALO","BREMEN","DALLAS","PEKING","AUCKLAND","ALEXANDRIA","CARACAS","HALIFAX","GENOA","COPENHAGEN","BERLIN","MANILA","REGINA","LENINGRAD","BANGKOK","MADRID","CANBERRA","CASABLANCA","ERIE","NICE","CHICAGO","KARACHI","DAKAR","MECCA","BAGHDAD","ADELAIDE","DACCA"]
    }
    
    public static func words_8710() -> [String] {
        return["LORY","TURKEY","JAY","MYNA","TIT","TUI","TOMTIT","SWAN","SKYLARK","SKUA","ROOSTER","SPARROW","SWALLOW","OWL","OWLET","CANARY","GROUSE","EMU","TERN","WREN","SNIPE","AUK","ROOK","IBIS","SHAG","EGRET","CHAT","ROC","TEAL","HEN","BUZZARD","QUETZEL","OSPREY","APTERYX","CASSOWARY","STILT","VULTURE","SWIFT","CYGNET","THRUSH","BOOBY","STORK","BUSTARD","TOUCAN","CROW","PARROT","PULLET","OSTRICH","ALBATROSS","FROGMOUTH","PIPIT","CURLEW","PEEWIT","BITTERN","LYREBIRD","STARLING","AVOCET","PLOVER","GOOSE","FOWL","KESTREL","BULBUL","PHEASANT","RAVEN","PENGUIN","PHOENIX","DOVE","GULL","LOON","LINNET","SEAGULL","WAGTAIL","QUAIL","CUCKOO","GANNET","PETREL","PUFFIN","HAWK","KITE","SANDPIPER","BANTAM","MOPOKE","SHRIKE","ROSELLA","COCKATOO","MOA","PEN","HERON","MACAW","ROBIN","WADER","LORIKEET","WHIPBIRD","PARTRIDGE","LOVEBIRD","ORIOLE","PIGEON","FANTAIL","DIPPER","HORNBILL","HARRIER","DODO","ERNE","BLUEBIRD","BOBOLINK","COCKATIEL","MAGPIE","JACKDAW","LARK","CRANE","FALCON","GANDER","MALLARD","PELICAN","COCK","RHEA","FINCH","PEACOCK","DRAKE","EIDER","GREBE","BELLBIRD","BLACKBIRD","EAGLE","KEA"]
    }
    
    public static func words_8705() -> [String] {
        return ["ZINNIA","MAY","ALYSSUM","SOW","PANSY","POPPY","AZALEA","GAZANIA","LOTUS","PEONY","DAISY","LILY","POT","PEST","STEM","SHRUBS","WORDSWORTH","OMARKHAYYAM","BOUQUET","DISPLAY","TULIP","WATTLE","SNOWDROP","GRASS","STOCK","NATIVES","TRIM","CACTUS","HYACINTH","BLOSSOM","ASTER","SWEEP","TREES","TUBER","WATER","TAP","CROCUS","ROSE","MOWER","PRUNE","STALK","VIOLET","LARKSPUR","IRIS","SOIL","FLOWERS","HIBISCUS","MIMOSA","PLANT","ROCKS","HOSE","LAWN","PATH","VINE","CYCLAMEN","JONQUIL","SALVIA","NITROGEN","HYDRANGEA","POOL","JASMIN","BROOM","MULCH","VIOLA","SPRINKLE","BUD","ANNUAL","BONSAI","LILIUM","CORM","IXIA","PLUMBAGO","CARNATION","EARTH","DISEASE","SAXIFRAGE","BULB","PINK","BLOOM","SPADE","SHAKESPEARE","VERBENA","BALSAM","FORK","PALM","SEED","WEED","ANEMONE","PREPARE","EDGES","FREESIA","ORGANIC","LANDSCAPE","PERENNIAL","FERN","MARIGOLD","DRAIN","GREEN","HOE","ORCHID","CALENDULA","CANNA","GARDEN","BEGONIA","CLIMBER","CAN","ALOE","RAKE","GARDENIA","CLARKIA","LOBELIA","CAMELLIA","DIG","DAFFODIL","LILAC","DAHLIA","LEAF","ACACIA","BED"]
    }
    
    public static func words_8702() -> [String] {
        return [ "EMBEZZLE","GAZUMP","BUY","SQUEEZE","PROXY","TRUST","PAY","SPOT","BUYER","UNITS","PARITY","MONEY","CUT","TAX","ASSETS","LOSS","PAYMENT","TRUSTEE","COST","MONOPOLY","SHORT","BONUS","NOTES","QUOTE","PROSPECTUS","CURRENCY","INVESTMENT","IOU","TIP","STOCK","JUMP","DISCOUNT","INTEREST","SETTLEMENT","FUNDS","YIELD","NET","OPTION","RIGHTS","SECURITIES","REPORT","SHARES","DEPOSIT","LIABILITY","CONTRACT","ACCOUNT","PREMIUM","RESERVE","REVENUE","PROFIT","SCRIP","SOLD","VENDOR","MARKET","GUARANTEE","BOOM","BULL","SELL","DEBENTURE","AGENT","DRAWER","DEFAULT","CREDITOR","INFLATION","PAR","CASH","RING","SALE","CORNER","RECEIPT","CARTEL","CHEQUE","CREDIT","MARGIN","ORDER","FIRM","CAPITAL","PERCENTAGE","RIG","BROKER","INCOME","MERGER","DEBIT","COLLATERAL","AVERAGE","BOND","DIVIDEND","EXCHANGE","PRICE","ADVICE","GOLD","OFFER","BANKER","JOBBER","BANK","FINANCE","BEAR","BILL","BALANCE","CALL","BID","DEAL","DEED"]
    }
    
    public static func words_8806() -> [String] {
        return [
            "GUY","YAW","STAY","PLY","BUOY","QUAY","JETTY","DORY","AHOY","SET",
            "YACHT","MAST","PORT","PROW","BOWSPRIT","TRANSOM","TRIM","ASTERN","BOW","BOX",
            "SPAR","HAWSER","JUNK","MOOR","SHIP","WATCH","CREW","AFT","SAIL","OAR",
            "TACK","LOG","FOG","MIZZEN","HORIZON","STORM","SEXTANT","VOYAGE","STERN","CUTTER",
            "HATCHWAY","GANGWAY","QUARTERS","JETTISON","KNOT","DINGHY","SLOOP","STEER","COURSE","SCUPPER",
            "WINDLASS","STEAMSHIP","SWELL","SQUALL","TOPSAIL","SLIP","SHEET","GALLEY","HYDROFOIL","STEAMBOAT",
            "OUTRIGGER","CAPSTAN","HALYARD","STEAMER","CANVAS","BUNK","DHOW","WIND","PENNANT","WINDWARD",
            "WEATHER","STARBOARD","SAILOR","SCHOONER","PAINTER","PITCH","SHOAL","NAUTICAL","NAVIGATE","ASHORE",
            "TANKER","SPINNAKER","BALLAST","FORWARD","BOOM","ROPE","ALOFT","BERTH","CHART","WHARF",
            "LUGGER","RUDDER","TILLER","TIDE","WAKE","LAUNCH","SPLICE","LIGHTER","CAULK","FLUKE",
            "HATCH","KETCH","WHEEL","CATAMARAN","FREIGHTER","PIER","FRIGATE","RIG","ANCHOR","LINER",
            "CLIPPER","LEEWARD","RIGGING","TACKLE","LIFEBOAT","INBOARD","PINNACE","LOCKER","GALLEON","BRIG",
            "HELM","HOLD","LINE","BULKHEAD","ANCHORAGE","BOLLARD","JIG","DOCK","RAKE","BLOCK",
            "ABOARD","CAREEN","BINNACLE","BRIDGE","CABIN","BEAM","ABEAM","BILGE","ALEE","DECK"]
    }
}
